server:
  port: "8080"
spring:
  datasource:
    url: jdbc:h2:mem:shopping_cart_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    data: classpath:/sql/product-h2.sql
  h2:
    console:
      enabled: "true"
      path: /h2-console
  queries:
    users-query: select username, password, active from user where username=?
    roles-query: select u.username, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.username=?
  admin:
    username: admin
    password: admin
  thymeleaf:
    cache: "false"
    prefix: classpath:/templates